from weasyprint import HTML

class ReportGenerator:
    def export_html(self, devices):
        # 1. Initialize HTML structure and Enterprise styling
        html_content = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>USB-TRACE Advanced Forensic Report</title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 30px; background-color: #f9f9f9; }
                h2 { color: #1a2a6c; border-bottom: 3px solid #1a2a6c; padding-bottom: 10px; }
                .header-info { margin-bottom: 20px; font-style: italic; color: #555; }
                table { border-collapse: collapse; width: 100%; background: white; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 13px; }
                th { background-color: #1a2a6c; color: white; text-transform: uppercase; }
                tr:nth-child(even) { background-color: #f2f2f2; }
                .HIGH-RISK { color: white; background-color: #e74c3c; font-weight: bold; padding: 5px; border-radius: 3px; display: inline-block; }
                .SUSPICIOUS { color: #333; background-color: #f1c40f; font-weight: bold; padding: 5px; border-radius: 3px; display: inline-block; }
                .NORMAL { color: white; background-color: #27ae60; font-weight: bold; padding: 5px; border-radius: 3px; display: inline-block; }
                .mitre-tag { background: #eee; border: 1px solid #ccc; padding: 3px 6px; border-radius: 4px; font-family: 'Courier New', Courier, monospace; font-size: 11px; font-weight: bold; color: #c0392b;}
                .ioc-box { font-size: 11px; color: #444; max-width: 250px; line-height: 1.4; }
                ul { margin: 0; padding-left: 20px; }
            </style>
        </head>
        <body>
            <h2>🛡️ USB-TRACE: Advanced Forensic Intelligence Report</h2>
            <div class="header-info">Generated by: Mohamed Kamal El-dein | ID: 1951710413</div>
            <table>
                <tr>
                    <th>Timestamp</th>
                    <th>Device Identity (VID:PID)</th>
                    <th>Threat Classification</th>
                    <th>MITRE ATT&CK ID</th>
                    <th>Attack Type</th>
                    <th>IoC Indicators</th>
                    <th>Mitigation Strategy</th>
                </tr>
        """

        # 2. Populate table rows with forensic data
        for device in devices:
            # Format mitigation actions into bullet points
            if device.mitigation_actions:
                mitigations = "<ul><li>" + "</li><li>".join(device.mitigation_actions) + "</li></ul>"
            else:
                mitigations = "No immediate action required."
            
            risk_status = getattr(device, 'risk_status', 'Normal')
            risk_class = risk_status.upper()
            
            # Fetch academic data (with fallbacks if older data structures are passed)
            mitre_id = getattr(device, 'mitre_id', 'N/A')
            attack_type = getattr(device, 'attack_type', 'N/A')
            ioc_indicators = getattr(device, 'ioc_indicators', 'N/A')

            html_content += f"""
                <tr>
                    <td>{device.insert_time}</td>
                    <td><b>{device.vendor_id}:{device.product_id}</b><br><small>{device.threat_name}</small></td>
                    <td><span class="{risk_class}">{risk_status}</span></td>
                    <td><span class="mitre-tag">{mitre_id}</span></td>
                    <td>{attack_type}</td>
                    <td class="ioc-box"><i>{ioc_indicators}</i></td>
                    <td>{mitigations}</td>
                </tr>
            """

        # 3. Close HTML tags
        html_content += """
            </table>
        </body>
        </html>
        """

        # 4. Save to disk
        with open("forensic_report.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        
        print("[+] Advanced HTML Forensic Report generated successfully: forensic_report.html")

    def export_pdf(self, devices):
        # Convert the generated HTML layout directly into a professional PDF document
        HTML('forensic_report.html').write_pdf('forensic_report.pdf')
        print("[+] Advanced PDF Forensic Report generated successfully: forensic_report.pdf")